apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-and-deploy-pl-
spec:
  pipelineRef:
    name: build-and-deploy
  params:
  - name: deployment-name
    value: python-sample
  - name: deployment
    value: k8s/deployment.yaml
  - name: git-url
    value: https://github.com/parthghetia-rh/roxctl-ocp-pipeline.git
  - name: IMAGE
    value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/python-sample
  - name: TLSVERIFY
    value: "false"
  - name: insecure-skip-tls-verify
    value: "true"
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
  - name: rox-api-token-auth
    secret:
      secretName: rox-api-token