apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: apply-manifests
  namespace: rox-ctl-pipeline
  annotations:
     argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
     argocd.argoproj.io/sync-wave: "802"
spec:
  workspaces:
  - name: source
  params:
    - name: manifest_dir
      description: The directory in source that contains yaml manifests
      type: string
      default: "k8s"
  steps:
    - name: apply
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo Applying manifests in $(inputs.params.manifest_dir) directory
          oc apply -f $(inputs.params.manifest_dir)
          echo -----------------------------------
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: update-deployment
  namespace: rox-ctl-pipeline
spec:
  params:
    - name: deployment
      description: The name of the deployment patch the image
      type: string
    - name: IMAGE
      description: Location of image to be patched with
      type: string
  steps:
    - name: patch
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      command: ["/bin/bash", "-c"]
      args:
        - |-
          oc patch deployment $(inputs.params.deployment) --patch='{"spec":{"template":{"spec":{
            "containers":[{
              "name": "$(inputs.params.deployment)",
              "image":"$(inputs.params.IMAGE)"
            }]
          }}}}'

          # issue: https://issues.redhat.com/browse/SRVKP-2387
          # images are deployed with tag. on rebuild of the image tags are not updated, hence redeploy is not happening
          # as a workaround update a label in template, which triggers redeploy pods
          # target label: "spec.template.metadata.labels.patched_at"
          # NOTE: this workaround works only if the pod spec has imagePullPolicy: Always
          patched_at_timestamp=`date +%s`
          oc patch deployment $(inputs.params.deployment) --patch='{"spec":{"template":{"metadata":{
            "labels":{
              "patched_at": '\"$patched_at_timestamp\"'
            }
          }}}}'
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: rhacs-image-scan
  namespace: rox-ctl-pipeline
  labels:
    app.kubernetes.io/version: "4.0"
  annotations:
    tekton.dev/tags: security
    tekton.dev/categories: Security
    tekton.dev/displayName: "Scan an image for vulnerabilities with Red Hat Advanced Cluster Security"
    tekton.dev/platforms: "linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,darwin/amd64,darwin/arm64,windows/amd64"
    tekton.dev/pipelines.minVersion: "0.50.0"
spec:
  description: >-
    Scan an image with Red Hat Advanced Cluster Security.

    This task allows you to return full vulnerability scan results for an image
    in CSV, Table, or JSON formats.
    The companion rhacs-image-check task checks an image against build-time policies.
  params:
    - name: rox_central_endpoint
      type: string
      description: The address:port tuple for RHACS Stackrox Central.
      default: central.stackrox.svc:443
    - name: rox_image
      description: Image providing the roxctl tool.
      default: quay.io/stackrox-io/roxctl:4.4.2
    - name: image
      type: string
      description: |
        Full name of image to scan.

        SHA 256 digest may be included to ensure scan of sequental runs with same tag.
        Examples: 'gcr.io/rox/sample:5.0-rc1', '$(params.IMAGE)', '$(params.IMAGE)@$(tasks.buildah.results.IMAGE_DIGEST)'
      default: '$(params.IMAGE)'
    - name: output_format
      type: string
      description: Results output format (json | csv | table)
      default: json
    - name: insecure-skip-tls-verify
      type: string
      description: |
        Do not verify TLS certificates.

        When set to "true", skip verifying the TLS certs of the Central endpoint and registry.
      default: "false"
    - name: rox_config_dir
      type: string
      description: |
        Path to the roxtl config directory within the roxctl-config workspace (if machine to machine authentication is used).
        Mutually exclusive with token_file.
        The path must be prefixed with "/roxctl-config".
      default: ""
    - name: rox_token_file
      description: |
        Path to the API Token file (if authentication through API token).
        Mutually exclusive with rox_config_dir.
        The path must be prefixed with "/rox-api-token-auth".
        Example "/rox-api-token-auth/rox_api_token"
      type: string
      default: ""
    - name: output_file
      type: string
      description: |
        Path to a file where to write the roxctl standard output stream.
        If empty, the output stream goes to the container standard output.
      default: ""
    - name: error_file
      type: string
      description: |
        Path to a file where to write the roxctl standard error stream.
        If empty, the error stream goes to the container standard error.
      default: ""
  workspaces:
    - name: roxctl-config
      description: |
        A workspace containing the configuration for roxctl. Used to authenticate with the remote central using short-lived tokens.
        Mutually exclusive with rox-api-token-auth workspace.
        The workspace has to be populated by a rhacs-m2m-authenticate TaskRun.
      optional: true
      readOnly: true
      mountPath: /roxctl-config
    - name: rox-api-token-auth
      description: |
        A workspace containing a rox token file. Used to authenticate with the remote central.
        Mutually exclusive with roxctl-config.
        It is strongly recommended that this workspace be bound to a Kubernetes secret.
      optional: true
      readOnly: true
      mountPath: /rox-api-token-auth
  steps:
    - name: rox-image-scan
      image: $(params.rox_image)
      env:
        - name: HOME
          value: /tekton/home
        - name: IMAGE
          value: $(params.image)
        - name: INSECURE
          value: $(params.insecure-skip-tls-verify)
        - name: OUTPUT
          value: $(params.output_format)
        - name: ROX_CONFIG_DIR
          value: $(params.rox_config_dir)
        - name: ROX_API_TOKEN_FILE
          value: $(params.rox_token_file)
        - name: ROX_ENDPOINT
          value: $(params.rox_central_endpoint)
        - name: ROX_EXECUTION_ENV
          value: Tekton
        - name: ROX_OUTPUT_FILE
          value: $(params.output_file)
        - name: ROX_ERROR_FILE
          value: $(params.error_file)
      args:
        - image
        - scan
        - --insecure-skip-tls-verify=$(INSECURE)
        - --output=$(OUTPUT)
        - --image=$(IMAGE)
---
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: rhacs-image-check
  namespace: rox-ctl-pipeline
  labels:
    app.kubernetes.io/version: "4.0"
  annotations:
    tekton.dev/tags: security
    tekton.dev/categories: Security
    tekton.dev/displayName: "Policy check an image with Red Hat Advanced Cluster Security"
    tekton.dev/platforms: "linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,darwin/amd64,darwin/arm64,windows/amd64"
    tekton.dev/pipelines.minVersion: "0.50.0"
spec:
  description: >-
    Policy check an image with Red Hat Advanced Cluster Security.

    This tasks allows you to check an image against build-time policies
    and apply enforcement to fail builds.  It's a companion to the
    rhacs-image-scan task, which returns full vulnerability scan
    results for an image.
  params:
    - name: rox_central_endpoint
      type: string
      description: The address:port tuple for RHACS Stackrox Central.
      default: central.stackrox.svc:443
    - name: rox_image
      description: Image providing the roxctl tool.
      default: quay.io/stackrox-io/roxctl:4.4.2
    - name: image
      type: string
      description: |
        Full name of image to check.
        Examples: 'gcr.io/rox/sample:5.0-rc1', '$(params.IMAGE)', '$(params.IMAGE)@$(tasks.buildah.results.IMAGE_DIGEST)'
      default: '$(params.IMAGE)'
    - name: output_format
      description: Results output format (csv | json | junit | table)
      type: string
      default: "table"
    - name: insecure-skip-tls-verify
      type: string
      description: |
        Do not verify TLS certificates.

        When set to "true", skip verifying the TLS certs of the Central endpoint and registry.
      default: "false"
    - name: rox_config_dir
      type: string
      description: |
        Path to the roxtl config directory within the roxctl-config workspace (if machine to machine authentication is used).
        Mutually exclusive with token_file.
        The path must be prefixed with "/roxctl-config".
      default: ""
    - name: rox_token_file
      description: |
        Path to the API Token file (if authentication through API token).
        Mutually exclusive with rox_config_dir.
        The path must be prefixed with "/rox-api-token-auth".
        Example "/rox-api-token-auth/rox_api_token"
      type: string
      default: ""
    - name: output_file
      type: string
      description: |
        Path to a file where to write the roxctl standard output stream.
        If empty, the output stream goes to the container standard output.
      default: ""
    - name: error_file
      type: string
      description: |
        Path to a file where to write the roxctl standard error stream.
        If empty, the error stream goes to the container standard error.
      default: ""
  workspaces:
    - name: roxctl-config
      description: |
        A workspace containing the configuration for roxctl. Used to authenticate with the remote central using short-lived tokens.
        Mutually exclusive with rox-api-token-auth workspace.
        The workspace has to be populated by a rhacs-m2m-authenticate TaskRun.
      optional: true
      readOnly: true
      mountPath: /roxctl-config
    - name: rox-api-token-auth
      description: |
        A workspace containing a rox token file. Used to authenticate with the remote central.
        Mutually exclusive with roxctl-config.
        It is strongly recommended that this workspace be bound to a Kubernetes secret.
      optional: true
      readOnly: true
      mountPath: /rox-api-token-auth
  results:
    - name: check_output
      description: Output of `roxctl image check`
  steps:
    - name: rox-image-check
      image: $(params.rox_image)
      env:
        - name: HOME
          value: /tekton/home
        - name: IMAGE
          value: $(params.image)
        - name: INSECURE
          value: $(params.insecure-skip-tls-verify)
        - name: OUTPUT
          value: $(params.output_format)
        - name: ROX_CONFIG_DIR
          value: $(params.rox_config_dir)
        - name: ROX_API_TOKEN_FILE
          value: $(params.rox_token_file)
        - name: ROX_ENDPOINT
          value: $(params.rox_central_endpoint)
        - name: ROX_EXECUTION_ENV
          value: Tekton
        - name: ROX_OUTPUT_FILE
          value: $(params.output_file)
        - name: ROX_ERROR_FILE
          value: $(params.error_file)
      args:
        - image
        - check
        - --insecure-skip-tls-verify=$(INSECURE)
        - --output=$(OUTPUT)
        - --image=$(IMAGE)
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: rhacs-deployment-check
  namespace: rox-ctl-pipeline
  labels:
    app.kubernetes.io/version: "4.0"
  annotations:
    tekton.dev/tags: security
    tekton.dev/categories: Security
    tekton.dev/displayName: "Policy check a deployment with Red Hat Advanced Cluster Security"
    tekton.dev/platforms: "linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,darwin/amd64,darwin/arm64,windows/amd64"
    tekton.dev/pipelines.minVersion: "0.50.0"
spec:
  description: >-
    Policy check a deployment with Red Hat Advanced Cluster Security.

    This tasks allows you to check a Kubernetes deployment manifest against policies
    and apply enforcement to fail pipelines.
  params:
    - name: rox_central_endpoint
      type: string
      description: The address:port tuple for RHACS Stackrox Central.
      default: central.stackrox.svc:443
    - name: rox_image
      description: Image providing the roxctl tool.
      default: quay.io/stackrox-io/roxctl:4.4.2
    - name: deployment
      type: string
      description: |
        Deployment filename to check.
        Examples: 'deployment.yaml', '$(workspaces.source.path)/base/deployment.yaml'
      default: '$(workspaces.source.path)/deployment.yaml'
    - name: output_format
      description: Results output format (csv | json | junit | table)
      type: string
      default: "table"
    - name: insecure-skip-tls-verify
      type: string
      description: |
        Do not verify TLS certificates.

        When set to "true", skip verifying the TLS certs of the Central endpoint and registry.
      default: "false"
    - name: rox_config_dir
      type: string
      description: |
        Path to the roxtl config directory within the roxctl-config workspace (if machine to machine authentication is used).
        Mutually exclusive with token_file.
        The path must be prefixed with "/roxctl-config".
      default: ""
    - name: rox_token_file
      description: |
        Path to the API Token file (if authentication through API token).
        Mutually exclusive with rox_config_dir.
        The path must be prefixed with "/rox-api-token-auth".
        Example "/rox-api-token-auth/rox_api_token"
      type: string
      default: ""
    - name: output_file
      type: string
      description: |
        Path to a file where to write the roxctl standard output stream.
        If empty, the output stream goes to the container standard output.
      default: ""
    - name: error_file
      type: string
      description: |
        Path to a file where to write the roxctl standard error stream.
        If empty, the error stream goes to the container standard error.
      default: ""
  workspaces:
    - name: source
    - name: roxctl-config
      description: |
        A workspace containing the configuration for roxctl. Used to authenticate with the remote central using short-lived tokens.
        Mutually exclusive with rox-api-token-auth workspace.
        The workspace has to be populated by a rhacs-m2m-authenticate TaskRun.
      optional: true
      readOnly: true
      mountPath: /roxctl-config
    - name: rox-api-token-auth
      description: |
        A workspace containing a rox token file. Used to authenticate with the remote central.
        Mutually exclusive with roxctl-config.
        It is strongly recommended that this workspace be bound to a Kubernetes secret.
      optional: true
      readOnly: true
      mountPath: /rox-api-token-auth
  results:
    - name: check_output
      description: Output of `roxctl deployment check`
  steps:
    - name: rox-deploy-check
      image: $(params.rox_image)
      workingDir: $(workspaces.source.path)
      env:
        - name: DEPLOYMENT
          value: $(params.deployment)
        - name: HOME
          value: /tekton/home
        - name: INSECURE
          value: $(params.insecure-skip-tls-verify)
        - name: OUTPUT
          value: $(params.output_format)
        - name: ROX_CONFIG_DIR
          value: $(params.rox_config_dir)
        - name: ROX_API_TOKEN_FILE
          value: $(params.rox_token_file)
        - name: ROX_ENDPOINT
          value: $(params.rox_central_endpoint)
        - name: ROX_EXECUTION_ENV
          value: Tekton
        - name: ROX_OUTPUT_FILE
          value: $(params.output_file)
        - name: ROX_ERROR_FILE
          value: $(params.error_file)
      args:
        - deployment
        - check
        - --insecure-skip-tls-verify=$(INSECURE)
        - --output=$(OUTPUT)
        - --file=$(DEPLOYMENT)